module uart_receiver_tb;
localparam CLK_PERIOD=40;
localparam CLKS_PER_BIT=217;
localparam BIT_TIME=CLK_PERIOD * CLKS_PER_BIT;
reg clk;
reg rst_n;
reg serial_in;
wire [7:0]data_out;
wire data_ready;
integer rx_count;
uart_receiver #(.CLKS_PER_BIT(CLKS_PER_BIT)) dut(.clk(clk),.rst_n(rst_n),.serial_in(serial_in),.data_out(data_out),.data_ready(data_ready));

always #(CLK_PERIOD/2) clk=~clk;

task send_uart_frame(input [7:0]payload);
	integer i;
	begin
		serial_in=1'b0; #(BIT_TIME);
		for(i=0;i<8;i=i+1)begin
			serial_in=payload[i];
			#(BIT_TIME);
		end

		serial_in=1'b1; #(BIT_TIME);
		end
	endtask
	always@(posedge clk)begin
		if(data_ready)begin
		rx_count<=rx_count+1;
	$display("RX[%0d] @ %0t ns=%h",rx_count,$time,data_out);
end
end
initial begin
	clk=1'b0;
	rst_n=1'b0;
	serial_in=1'b1;
	rx_count=0;
	#(10*CLK_PERIOD);
	rst_n=1'b1;
	#(5*CLK_PERIOD);
	send_uart_frame(8'h3C);
	#(BIT_TIME);
	send_uart_frame(8'h2F);
	#(3*BIT_TIME);
	send_uart_frame(8'h3E);
	#(3*BIT_TIME);

	$display("final data_out=%h",data_out);
	if(rx_count==3)
	$display("pass : 3 bytes received succesfully");
else
	$display("fail : expected 3 bits to pass but %d bits passed",rx_count);
#(5*CLK_PERIOD);
$finish;
end
initial begin
	$dumpfile("uart_receiver.vcd");
	$dumpvars(0,uart_receiver_tb);
end
endmodule
